config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/sign_in_without_email', to: 'omniauth_callbacks#sign_in_without_email'
    post '/create_user_without_email', to: 'omniauth_callbacks#create_user_without_email'
  end

  concern :voted do
    post :like, :dislike
    delete :unvote
  end

  concern :commented do
    post :create_comment
    delete :delete_comment
  end

  resource :search, only: :index do
    get 'search', to: 'searches#search'
  end

  post '/', to: proc { [200, {}, ['']] }
  post '/questions/10', to: proc { [200, {}, ['']] }
  delete '/', to: proc { [200, {}, ['']] }

  resources :questions, concerns: %i[voted commented] do
    patch :delete_attachment
    resources :answers, concerns: %i[voted commented] do
      patch :select_best
      patch :delete_attachment
    end
  end

  resources :subscriptions, only: %i[create destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root 'questions#index'
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, presence: true
  has_many :answers
  has_many :attachments, as: :attachable
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
  has_many :subscriptions
  belongs_to :user
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def count_voices
    all_voices = 0
    self.votes.each do |vote|
      all_voices += vote.opinion
    end
    all_voices
  end

  def check_for_user(current_user)
    self.votes.each do |vote|
      return false if vote.user_id == current_user.id
    end
    true
  end

  def self.list_of_questions
    questions = []
    now = DateTime.now.to_i
    find_each.each do |question|
      time_diff = (now - question.created_at.to_i) / 86_400
      questions.push(question) if time_diff < 1
    end
    questions
  end
end

app/controllers/api/v1/questions_controller.rb
module Api
  module V1
    class QuestionsController < Api::BaseController

      def create
        respond_with(authorize(@question = Question
          .create(question_params.merge(user_id: current_resource_owner.id))))
      end

      def index
        @questions = Question.all
        respond_with @questions
      end

      def show
        @question = Question.find(params[:id])
        respond_with @question
      end

      private

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show edit update destroy]
  before_action :find_question_vote, only: %i[like dislike unvote create_comment delete_comment]
  before_action :build_answer, only: :show
  before_action :find_question_attachment, only: :delete_attachment
  before_action :find_attachment, only: :delete_attachment
  after_action :create_subscription, only: [:create]
  after_action :perform, only: [:create]
  after_action :publish_comment, only: [:create_comment]

  include Voted
  include Commented

  respond_to :js, only: %i[update edit]

  def new
    @question = Question.new
  end

  def delete_attachment
    authorize @question
    @attachment.destroy
    respond_with @question
  end

  def index
    @questions = Question.all
  end

  def create
    respond_with(authorize(@question = Question.create(question_params.merge(user_id: current_user.id))))
  end

  def show
    respond_with @question
  end

  def edit
  end

  def update
    authorize @question
    @question.update(question_params)
  end

  def destroy
    authorize @question
    @question.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def perform
    ActionCable.server.broadcast 'questions_channel', { question: render_question(current_user, @question) }
  end

  def render_question(user, question)
    ApplicationController.render_with_signed_in_user(user,
                                                     partial: 'questions/question',
                                                     locals: { question: question })
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_question_attachment
    @question = Question.find(params[:question_id])
  end

  def find_question_vote
    @instance = Question.find(params[:question_id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[file _destroy])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def find_attachment
    @attachment = Attachment.find(params[:attachment_id])
  end

  def create_subscription
    @question.subscriptions.create(user_id: current_user.id, question_id: @question.id) if @question.save
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
- @question.answers.best_sort.each do |answer|
  p
    -cache answer do
      div class="body_answer_#{answer.id}" id="body_answer_#{answer.id}" style="padding: 20px;margin: 0px 0px 20px 0px;position: relative;margin-right: 12px;"
        .container class="container-answer"
          .row class="row-answer"
            - if answer.persisted?
              .col-lg-2 = answer.body
              - if answer.best == true
                .col-lg-1 Best
              .rating-div
                .col-lg-1= "Rating: #{answer.count_voices}"
              - if answer.attachments[0] != nil && answer.attachments[0].persisted?
                .col-lg-1 Attachments:
                .col-lg-2
                  - answer.attachments.each do |a|
                    - if a.persisted?
                      .row
                        = link_to a.file.identifier, a.file.url
              - if answer.attachments[0] != nil && answer.attachments[0].persisted? && policy(answer).delete_attachment?
                .col-lg-2
                  - answer.attachments.each do |a|
                    .row= button_to 'Delete this file', question_answer_delete_attachment_path(@question, answer, attachment_id: a),
                              method: :patch, remote: true
              -if policy(answer).update?
                .col-lg-2 class="edit-answer-form"
                  .row= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
                  .row = link_to 'Delete', question_answer_path(@question, answer),
                          remote: true, method: :delete, class: 'delete-answer-link'
                  .row class="edit-answer-row"
                    = form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |form|
                      = form.text_area :body, class: "input-edit-answer", id: "input-answer-id"
                      = form.submit 'Save', class: "edit-save-answer-link-#{answer.id}", id: "edit-save-answer-link-#{answer.id}"
              - if answer.best != true && policy(answer).select_best?
                .col-lg-2= button_to 'Select answer as best', question_answer_select_best_path(@question, answer),
                        method: :patch, remote: true
              -if policy(answer).like?
                .col-lg-1= link_to 'Vote', '', class: 'vote-answer-link', remote: true, data: { answer_id: answer.id, flag: answer.check_for_user(current_user) }
              .links-for-voting style="display:none"
                .col-lg-2
                  .row= link_to 'Vote for', '', class: 'vote-for-answer-link',
                          method: :post, remote: true, data: { question_id: @question.id, answer_id: answer.id }
                  .row= link_to 'Vote against', '', class: 'vote-against-answer-link',
                          method: :post, remote: true, data: { question_id: @question.id, answer_id: answer.id }
              .link-for-deleting style="display:none"
                .col-lg-2
                  = link_to 'Delete vote', '', class: 'vote-delete-answer-link',
                        method: :delete, remote: true, data: { question_id: @question.id, answer_id: answer.id }
                  p
          .comment-section
            .row class="comments-row-answers_#{answer.id}"
              - if !answer.comments[0].nil? && answer.comments[0].persisted?
                strong Comment section for answer
              - answer.comments.each do |comment|
                -cache comment do
                  .row style="padding: 20px;margin: 0px 0px 20px 0px;position: relative;"
                    .col-lg-3
                      = comment.view
                    -if policy(comment).delete_comment?
                      .col-lg-2
                        = link_to 'Delete comment', question_answer_delete_comment_path(question_id: @question.id, answer_id: answer.id), method: :delete
            -if policy(Comment).create_comment?
              .row
                .col-lg-2
                  = form_with url: "/questions/#{@question.id}/answers/#{answer.id}/create_comment", method: :post do |form|
                    .row
                      = form.label :body, 'Enter your comment for this answer'
                    .row
                      = form.text_area :view
                    .row
                      = form.submit "Comment"

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    = f.file_field :file
  = link_to_remove_association "remove file", f

app/views/questions/_question.html.slim
p
  div id="body_question_#{question.id}"
    .container class="question-container"
      .row class="question-row"
        .col-lg-2= question.title
        .col-lg-1= link_to 'Show', question
        - if policy(Subscription).create?
          - if Subscription.exists(current_user, question)
            .col-lg-1
              = link_to 'Unsubscribe',
                      subscription_path(Subscription.exists(current_user, question)), method: :delete
          - if !Subscription.exists(current_user, question)
            .col-lg-1
              = link_to 'Subscribe',
                      subscriptions_path(question_id: question.id, user_id: current_user.id), method: :post
        .rating-div
          .col-lg-1= " Rating: #{question.count_voices}"
        - if policy(question).like?
          .col-lg-1= link_to 'Vote', '', class: 'vote-question-link',
                  remote: true, data: { question_id: question.id, flag: question.check_for_user(current_user) }
          .links-for-voting class="links-question-voting" style="display:none"
            .col-lg-2 class="col-for"
              .row class="question-for"= link_to 'Vote for', '', class: 'vote-for-question-link',
                      method: :post, remote: true, data: { question_id: question.id }
              .row= link_to 'Vote against', '', class: 'vote-against-question-link',
                      method: :post, remote: true, data: { question_id: question.id }
          .link-for-deleting style="display:none"
            .col-lg-2= link_to 'Delete vote', '', class: 'vote-delete-question-link',
                    method: :delete, remote: true, data: { question_id: question.id }
        - if policy(question).update?
          .col-lg-1
            .row= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: question.id }
            .row= button_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }
          .col-lg-3
            = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |form|
              = form.text_field :title
              = form.text_area :body
              = form.submit 'Save'
          p

app/views/questions/index.html.slim
h1 Questions
.questions class="questions-index"
  - @questions.each do |question|
    = render partial: "questions/question", locals: { question: question }

.search_objects
  -if !@results.nil?
    h3 Search
    -@results.each do |result|
      .row style="background:white; margin-top:5px; border-radius:10px"
        -if result.respond_to?(:title)
          .col-md-2
            strong= result.title
        -if result.respond_to?(:body)
          .col-md-6
            =result.body
        - if result.respond_to?(:view)
          .col-md-6
            = result.view

app/views/questions/new.html.slim
h2 Ask new question
= form_for @question do |f|
  p
    = f.label :title
  p
    = f.text_field :title
  p
    = f.label :body
  p
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |attachment|
      = render 'attachment_fields', f: attachment
    .links
      = link_to_add_association 'add file', f, :attachments
  p
    = f.submit 'Create'

app/views/questions/show.html.slim
-cache @question do
  h2= @question.title
  p= @question.body
  .container
    .row
      - if @question.attachments[0] != nil && @question.attachments.first.persisted?
        .col-lg-1 Attachments:
      -@question.attachments.each do |a|
        -if a.persisted?
          .col-lg-2
            .row
              = link_to a.file.identifier, a.file.url
          -if @question.user == current_user
            .col-lg-1
              .row
                =link_to 'Delete this file', question_delete_attachment_path(@question, attachment_id: a), method: :patch
    .comment-question
      .row class="comments_row_#{@question.id}"
        h4 Comment section for question
        -@question.comments.each do |comment|
          - if comment.persisted?
            - cache comment do
              .row style="padding: 10px;margin: 0px 0px 10px 0px;position: relative;"
                .col-lg-3
                  = comment.view
                .col-lg-2
                  -if policy(comment).delete_comment?
                    =link_to 'Delete comment', question_delete_comment_path(@question), method: :delete
      -if policy(Comment).create_comment?
        .row
          .col-lg-2
            -cache ['comment_form', @question] do
              = form_with url: "/questions/#{@question.id}/create_comment", method: :post do |form|
                .row
                  = form.label :body, 'Enter your comment for this question'
                .row
                  = form.text_area :view
                .row
                  = form.submit "Comment"
  h2 Answers
  .answers class="answers-all"
    = render "answers"
  -if policy(Answer).create?
    p
      =link_to 'Ask new answer', '', class: 'ask-new-answer'
    = form_for [@question, @answer], remote: true do |f|
      p
        = f.label :body, 'Enter your answer'
      p
        .answer-errors
      p
        = f.text_area :body, class: 'answer_body'
      p Attachments:
      p
        = f.fields_for :attachments, @answer.attachments.build do |attachment|
          = render 'attachment_fields', f: attachment
        .links
          = link_to_add_association 'add file', f, :attachments
      p
        = f.submit 'Send', class: 'submit-form-new-answer'

app/views/questions/update.js.erb
$('#body_question_<%= @question.id %>').replaceWith('<%= j render @question %>');
$('.edit-question-link').click(function (e) {
    e.preventDefault();
    $(this).hide();
    let question_id = $(this).data('questionId');
    $('form#edit-question-' + question_id).show();
});