config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/sign_in_without_email', to: 'omniauth_callbacks#sign_in_without_email'
    post '/create_user_without_email', to: 'omniauth_callbacks#create_user_without_email'
  end

  concern :voted do
    post :like, :dislike
    delete :unvote
  end

  concern :commented do
    post :create_comment
    delete :delete_comment
  end

  resource :search, only: :index do
    get 'search', to: 'searches#search'
  end

  post '/', to: proc { [200, {}, ['']] }
  post '/questions/10', to: proc { [200, {}, ['']] }
  delete '/', to: proc { [200, {}, ['']] }

  resources :questions, concerns: %i[voted commented] do
    patch :delete_attachment
    resources :answers, concerns: %i[voted commented] do
      patch :select_best
      patch :delete_attachment
    end
  end

  resources :subscriptions, only: %i[create destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root 'questions#index'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = action_cable_meta_tag
    title= content_for?(:title) ? yield(:title) : "Qna"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_pack_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', skip_pipeline: true
    = javascript_pack_tag "application"
      /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
  body style="min-height: 95vh;display: flex;flex-direction: column;"
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"Q&A
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Search', search_search_path
            -if user_signed_in?
              li= link_to current_user.email, ''
              li= link_to "Exit", destroy_user_session_path, method: :delete
            -else
              li= link_to "Sign in", new_user_session_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield


  .footer style="margin-top: auto;"
    .container
      .row
        .col-lg-9
          - if policy(Question).create?
            p
              = link_to 'Ask new question', new_question_path
          p Pavel Tishkov &copy; Gotoinc 2021